### ISSUE TITLE
Docs improve with example how to use ssh key with ansible-run

### ISSUE THREAD

**Issue by IvanTurgenev1** [crossplane-contrib/provider-ansible#129]
### What problem are you facing?
at the moment it is not entirely clear how to use the ssx key to connect to remote hosts while using this provider
### How could Crossplane help solve your problem?
improve the documentation by adding an example of a similar case

**Comment by fahedouch** [comment]
Hi @IvanTurgenev1,

You can add the credentials to this list (e.g..: ssh keys)  https://github.com/crossplane-contrib/provider-ansible/blob/main/examples/provider/config.yaml#L19-L25

and then configure the keys file from you playbook tasks

PR is welcome :) 

Tell me if you need some help on this!

**Comment by IvanTurgenev1** [comment]
> Hi @IvanTurgenev1,
> 
> You can add the credentials to this list (e.g..: ssh keys) https://github.com/crossplane-contrib/provider-ansible/blob/main/examples/provider/config.yaml#L19-L25
> 
> and then configure the keys file from your playbook tasks
> 
> PR is welcome :)
> 
> Tell me if you need some help on this!

thanks for your reply!
it would be great to see an example of such usage
smth like this?
```
apiVersion: ansible.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: ssh-key
spec:
  credentials:
    - filename: ssh-key.json
      source: Secret
      secretRef:
        namespace: crossplane-system
        name: ssh-key
        key: key
```

```
apiVersion: v1
kind: Secret
metadata:
  namespace: crossplane-system
  name: ssh-key
type: Opaque
data:
  key: ssh_private_key_placeholder
```


> and then configure the keys file from your playbook tasks
```
apiVersion: ansible.crossplane.io/v1alpha1
kind: AnsibleRun
metadata:
  annotations:
    ansible.crossplane.io/runPolicy: ObserveAndDelete
  name: remote-test
spec:
  forProvider:
    playbookInline: |
      ---
      - hosts: test-host.local
        tasks:
          - name: taskname
            ...
  providerConfigRef:
    name: ssh-key
---
```
smth like that?

**Comment by fahedouch** [comment]
@IvanTurgenev1  would you please open a new PR with this inputs

**Comment by IvanTurgenev1** [comment]
@fahedouch 
i'm trying to put key by following code:
```
apiVersion: ansible.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: provider-config-example
spec:
  credentials:
    - filename: ./env/ssh-key
      source: Secret
      fs:
       path: ./env
      secretRef:
        namespace: crossplane-system
        name: ssh-credentials
        key: ssh-credentials
```
but file created in ansibleDir/GUID/ssh-key

how to create it inside env directory ? 
if follow this doc https://ansible-runner.readthedocs.io/en/stable/intro/#inputdir 
we should put ssh_key intro env dir
