### ISSUE TITLE
observe failed: Error decoding results

### ISSUE THREAD

**Issue by IvanTurgenev1** [crossplane-contrib/provider-ansible#147]
#What happened?
Error when i'm trying to use policy CheckWhenObserve
"message": "observe failed: Error decoding results\n\tread /dev/stdout: bad file descriptor",

#How can we reproduce it?
Just run simply task with file change
```
apiVersion: ansible.crossplane.io/v1alpha1
kind: AnsibleRun
metadata:
  name: test-remote
  annotations:
    ansible.crossplane.io/runPolicy: CheckWhenObserve
spec:
  forProvider:
    playbookInline: |
      ---
      - hosts: <HOST> ansible_ssh_private_key_file=ssh_key ansible_ssh_user=ansible_ops
        tasks:
          - name: ansibleplaybook-simple
            ansible.builtin.lineinfile:
             dest: /root/config_ssh
             regexp: '^PermitRootLogin'
             line: "PermitRootLogin yes"
             state: present
  providerConfigRef:
   name: provider-config-example
```
