### ISSUE TITLE
Support private git repos that require a custom CA cert

### ISSUE THREAD

**Issue by ron1** [crossplane-contrib/provider-ansible#171]
### What problem are you facing?
The ansible provider does not currently allow retrieval of Ansible content from git repos that require a custom CA certificate. This is a blocker for enterprise environments that define their own custom CA.

### How could Crossplane help solve your problem?
Enhance provider configuration to allow specification of a custom ca-bundle.crt. Then use that ca-bundle.crt when downloading remote ansible content.

**Comment by ron1** [comment]
Do you think the workaround described [here:]( https://github.com/crossplane/crossplane/issues/2535#issuecomment-907634643) for the aws provider might work for this provider as well? If so, is there an environment variable like AWS_CA_BUNDLE that would work to tell ansible where to find its ca-bundle.crt?

**Comment by fahedouch** [comment]
Hi @ron1 ,

We support mount and exposing the CA certificate to the controller pod through `ProviderConfig` :

```
apiVersion: ansible.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: config
spec:
  vars:
    # Specify the path where the Ansible roles are located
    SSL_CERT_FILE: ./ca.pem
  credentials:
    - filename: ca.pem
      source: Secret
      secretRef:
        namespace: crossplane-system
        name: secret-that-holds-ca-crt
        key: ca

--------------
> Do you think the workaround described [here](https://github.com/crossplane/crossplane/issues/2535#issuecomment-907634643) for the aws provider might work for this provider as well? If so, is there an environment variable like AWS_CA_BUNDLE that would work to tell ansible where to find its ca-bundle.crt when fetching urls?

Yes, I believe that you can CA certificate to the ansible controller certificate bundle using `Cluster Policy` from `kyverno`

Yes. Environment variables `SSL_CERT_FILE` and `SSL_CERT_DIR` can be used to specify additional trusted CA certificate or certificates ( [origin](https://github.com/ansible/ansible/issues/28570#issuecomment-324517881) ) . Please  note that we are running  `ansible-galaxy` binary  behind the scene to fetch ansible content, so we support ansible default environnement variable.

**Comment by ron1** [comment]
Hi @fahedouch,

Thanks for your response.

Is there a current work-around that can be used with the latest `provider-ansible` image to allow `ansible-galaxy` to pull from private git repos, say via`git+ssh` URLs? Are there environment variables (and volume mounts?) that can be dynamically added to the Pod that might help implement such a work-around?

**Comment by fahedouch** [comment]
> Hi @fahedouch,
> 
> Thanks for your response.
> 
> So, should we be able to set environment variables `SSL_CERT_FILE` and `SSL_CERT_DIR` via a mutating webhook in the latest `provider-ansible` image to allow `ansible-galaxy` to pull content from private git repos?

Yes.

**Comment by ride808** [comment]
Tried to do this via ProviderConfig but it's now expecting a key/value format.  THis:

```
apiVersion: ansible.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: provider-ansible
spec:
  vars:
    - key: SSL_CERT_FILE
      value: ./ca.pem
  credentials:
    - filename: sshkey
      source: Secret
      secretRef:
        key: sshkey
        name: ssh-key
        namespace: default
    - filename: ca.pem
      source: Secret
      secretRef:
        key: myca
        name: myca
        namespace: default
```

The ca.pem gets created in provider, but I'm not seeing the SSL_CERT_FILE env variable as being set when shelling into the container.  Also - how about user/pass for ansible-galaxy if pulling collections from a repo requiring auth as well?
