### ISSUE TITLE
Long Running ansibleRuns hang if they take longer than a minute to finish

### ISSUE THREAD

**Issue by eljohnson92** [crossplane-contrib/provider-ansible#175]
### What happened?

While testing a role I noticed at a certain point it starts to hang, I have distilled it to a simple playbook to reproduce it, it looks like if an ansibleRun takes longer than around 60 seconds to finish the process hangs and never finishes.

### How can we reproduce it?

I have slightly modified the example playbook yaml to reproduce this
```yaml
apiVersion: ansible.crossplane.io/v1alpha1
kind: AnsibleRun
metadata:
  name: example
spec:
  forProvider:
    # AnsibleRun default to using a remote source.
    # For simple cases you can use an inline source to specify the content of
    # playbook.yaml as opaque, inline yaml.
    playbookInline: |
      ---
      - hosts: localhost
        tasks:
          - name: Pause for 5 minutes to build app cache
            ansible.builtin.pause:
              seconds: 60
          - name: ansibleplaybook-simple
            debug:
              msg: Your are running 'ansibleplaybook-simple' example
```

in the debug logs I can see the following output showing the process does not finish
```
  68 [WARNING]: provided hosts list is empty, only localhost is available. Note that
  69 the implicit localhost does not match 'all'
  70
  71 PLAY [localhost] ***************************************************************
  72
  73 TASK [Gathering Facts] *********************************************************
  74 ok: [localhost]
  75
  76 TASK [Pause for 5 minutes to build app cache] **********************************
  77 Pausing for 61 seconds
  78 (ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
  79 1.673569115914057e+09   DEBUG   provider-ansible        Cannot observe external resource        {"controller": "managed/ansiblerun.ansible.crossplane.io", "request": "upbound-system/example", "uid": "23eddcf4-e6a5-        4cc7-8e4a-4d3ea558fff5", "version": "735728", "external-name": "example", "error": "signal: killed"}
```
in the container, I can also see a pretty strange `ps` output
```
PID   USER     TIME  COMMAND
    1 ansible   0:58 crossplane-ansible-provider --debug
   22 ansible   0:08 [ansible-playboo]
```
### What environment did it happen in?
Crossplane version: 1.10.1
provider-ansible version: main
