### ISSUE TITLE
Add git ssh auth support

### ISSUE THREAD

**Issue by ron1** [crossplane-contrib/provider-ansible#197]
### What problem are you facing?
Some environments rely on gith ssh based auth for private repositories instead of the currently supported token one.

The Upbound provider-terraform shares this problem as described [here](https://github.com/upbound/provider-terraform/issues/53).

### How could Crossplane help solve your problem?
Extend the current code around [credentials setup](https://github.com/crossplane-contrib/provider-ansible/blob/51173d0b555da2aca7763a1da08f11700be9afa9/internal/controller/ansibleRun/ansibleRun.go#L210-L228) with ssh support.

This code is similar to the code in provider-terraform around [credentials setup]((https://github.com/upbound/provider-terraform/blob/main/internal/controller/workspace/workspace.go#L180-L204).

**Comment by glennpratt** [comment]
If you'd like a monstrously terrible hack workaround:

```
apiVersion: ansible.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: {{ $myName }}
spec:
  credentials:
  - filename: .git-credentials-{{ $now }}
    source: Secret
    secretRef:
      namespace: mynamespace
      name: git-deploy-secret
      key: sshPrivateKey
  vars:
    - key: GIT_SSH_COMMAND
      value: ssh -i $(find /ansibleDir -name '.git-credentials-{{ $now }}' -maxdepth 2 -mindepth 2 | head -n1)
```
