### ISSUE TITLE
CheckWhenObserve does not trigger the run

### ISSUE THREAD

**Issue by mrdunski** [crossplane-contrib/provider-ansible#261]
### What happened?

I'm using inlinePlaybook with a private Galaxy Collection, similar to the following:

```yaml
apiVersion: ansible.crossplane.io/v1alpha1
kind: AnsibleRun
metadata:
  name: longhorn-backup-source
  namespace: crossplane-system
  annotations:
    ansible.crossplane.io/runPolicy: CheckWhenObserve
spec:
  forProvider:
    inventoryInline: |
      all:
        children:
          servers:
            hosts:
              "host1":
          agents:
            hosts:
              "host2":
              "host3":
    playbookInline: |
      ---
      - hosts: servers
        collections:
          - some.collection
        roles:
          - longhorn-backup-source
  providerConfigRef:
    name: galaxy-collection
```

When I run the playbook manually `ansible-playbook -i hosts.yml playbookInline.yml --check` I get a result:
```
(...)
PLAY RECAP ***********************************************************************************************************************************************************************************************
host1              : ok=46   changed=3    unreachable=0    failed=0    skipped=19   rescued=0    ignored=0 
```

But provider prints the following:
```
2023-10-08T17:22:10Z	DEBUG	provider-ansible	Reconciling	{"controller": "managed/ansiblerun.ansible.crossplane.io", "request": "crossplane-system/longhorn-backup-source"}
2023-10-08T17:22:35Z	DEBUG	provider-ansible	External resource is up to date	{"controller": "managed/ansiblerun.ansible.crossplane.io", "request": "crossplane-system/longhorn-backup-source", "uid": "ef4b1af1-1094-41b4-94ce-58ab72e275aa", "version": "224322497", "external-name": "longhorn-backup-source", "requeue-after": "2023-10-08T17:23:35Z"}
```

The run is not triggered.

Is there anything wrong in my configuration?

### How can we reproduce it?

I'm not really sure about specifics. It happens for me with many types of playbooks.

### What environment did it happen in?
* Crossplane: v1.13.2
* Kubernetes: v1.28.2+rke2r1

**Comment by mrdunski** [comment]
I've tried the following as well:
```yaml
apiVersion: ansible.crossplane.io/v1alpha1
kind: AnsibleRun
metadata:
  name: test-run
  namespace: crossplane-system
  annotations:
    ansible.crossplane.io/runPolicy: CheckWhenObserve
spec:
  forProvider:
    playbookInline: |
      ---
      - hosts: localhost
        tasks:
          - name: simple-playbook
            debug:
              msg: You are running 'simple-playbook'
            changed_when: true
```
