### ISSUE TITLE
CheckWhenObserve mode broken b/c ansible logs are not valid json

### ISSUE THREAD

**Issue by d-honeybadger** [crossplane-contrib/provider-ansible#290]
### What happened?

In `CheckWhenObserve` mode, reconciliation always fails with `observe failed: Error decoding results\n\tinvalid character` error. This error comes from provider-ansible attempting to parse ansible logs: https://github.com/crossplane-contrib/provider-ansible/blob/5e0d99269289a6c47b232d829eff424cfa374087/internal/controller/ansibleRun/ansibleRun.go#L363
The function `results.ParseJSONResultsStream`  expects logs in *json* format (e.g. something you'd get using [json callback](https://docs.ansible.com/ansible/latest/collections/ansible/posix/json_callback.html#ansible-collections-ansible-posix-json-callback). so, when trying to parse "classic" non-json ansible logs it, natually, fails.

### How can we reproduce it?

Create any resource with CheckWhenObserve policy.
Here's my example:
```
apiVersion: ansible.crossplane.io/v1alpha1
kind: AnsibleRun
metadata:
  annotations:
    ansible.crossplane.io/runPolicy: CheckWhenObserve
  name: example-add-line
spec:
  forProvider:
    inventoryInline: |2
      cluster:
        hosts:
          default-0:
            ansible_host: <IP>
    playbookInline: |2
      - name: add-line-to-file
        hosts: cluster
        tasks:
        - name: Add a line to file
          ansible.builtin.lineinfile:
            path: /root/testfile
            line: added-line
            state: present
    vars:
      ansible_ssh_private_key_file: ./ssh_id
  providerConfigRef:
    name: example
```

Observe the following status:
```
status:
  atProvider: {}
  conditions:
  - lastTransitionTime: "2024-01-17T21:57:05Z"
    message: "observe failed: Error decoding results\n\tinvalid character 'P' looking
      for beginning of value"
    reason: ReconcileError
    status: "False"
    type: Synced
```

Note that the same playbook succeeds in `ObserveAndDelete` mode.

### What environment did it happen in?
Crossplane version:
1.14.0
