### ISSUE TITLE
Ansible collections optionally depend on distlib, but that is missing

### ISSUE THREAD

**Issue by glennpratt** [crossplane-contrib/provider-ansible#316]
<!--
Thank you for helping to improve Crossplane!

Please be sure to search for open issues before raising a new one. We use issues
for bug reports and feature requests. Please find us at https://slack.crossplane.io
for questions, support, and discussion.
-->

### What problem are you facing?
<!--
Please tell us a little about your use case - it's okay if it's hypothetical!
Leading with this context helps frame the feature request so we can ensure we
implement it sensibly.
--->

The `manifest` directive in Ansible Collections galaxy.yml depends on the Python module `distlib`.

https://docs.ansible.com/ansible/latest/dev_guide/developing_collections_distributing.html#manifest-directives

While that is normally only required for a build, it is also required when installing a collection from Git.

### How could Crossplane help solve your problem?
<!--
Let us know how you think Crossplane could help with your use case. 
-->

Add the `distlib` Python module to the docker image.

#### Workaround

```yaml
apiVersion: pkg.crossplane.io/v1beta1                                                                                                                                                     
kind: DeploymentRuntimeConfig                                                                                                                                                             
metadata:                                                                                                                                                                                                                                                                                                                                            
  name: provider-ansible-config                                                                                                                                                                                                                                                                                                     
spec:                                                                                                                                                                                     
  deploymentTemplate:                                                                                                                                                                     
    spec:                                                                                                                                                                                 
      selector: {}                                                                                                                                                                        
      template:                                                                                                                                                                           
        spec:                                                                                                                                                                             
          containers:                                                                                                                                                                                                                                                                                                                                 
            command:                                                                                                                                                                      
            - /usr/bin/dumb-init                                                                                                                                                          
            - sh                                                                                                                                                                          
            - -c                                                                                                                                                                          
            - /usr/local/bin/pip install distlib && exec "$@"                                                                                                                             
            - --                                                                                                                                                                          
            - crossplane-ansible-provider                                                                                                                                                 
            name: package-runtime  
```
