### ISSUE TITLE
Cannot configure Git credentials

### ISSUE THREAD

**Issue by malins** [crossplane-contrib/provider-ansible#335]
Hello,

I'm trying to install a role from a private repository at github, but I do not succeed.

I'm using latest version of this provider (0.6.0).

My provider configuration looks like this:

```
apiVersion: ansible.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: ansible-test
spec:
  credentials:
  - filename: .git-credentials
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: git-credentials
      key: .git-credentials
```
 
My secret contains the credentials in the following format:

`https://malins:redacted@github.com`

Then, I reference my role in the ansiblerun resource:

```
apiVersion: ansible.crossplane.io/v1alpha1
kind: AnsibleRun
metadata:
  name: example
spec:
  forProvider:
    inventoryInline: |
      [...]
    roles:
    - name: myrole
      src: https://github.com/malins/myrole.git
    vars:
      [...]
  providerConfigRef:
    name: ansible-test 
```

The error I'm getting is:

```
connect failed: failed to install galaxy collections/roles: [WARNING]: - myrole was NOT installed successfully: - command /usr/bin/git clone
https://github.com/malins/myrole.git myrole failed in
directory /home/ansible/.ansible/tmp/ansible-local-243zzwzx8cq/tmp2sx5cq34
(rc=128) - Cloning into 'myrole'... fatal: could not read Username for
'https://github.com': No such device or address
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
No config file found; using defaults
Starting galaxy role install process: exit status 1
```

I tried to exec into the pod and issue the command "git config --global credential.helper store" -- and suddenly it start working.

Any help appreciated. Thank you

Manuel
