### ISSUE TITLE
Provider-ansible providerrevision unhealthy with crossplane >= v1.15

### ISSUE THREAD

**Issue by d-honeybadger** [crossplane-contrib/provider-ansible#346]
### What happened?

Updated Crossplane to v1.16 and provider-ansible providerrevision went unhealthy. The error is 
```
cannot unpack package: failed to fetch package digest from remote: failed to fetch package descriptor with a GET request after a previous HEAD request failure: GET https://xpkg.upbound.io/service/token?scope=repository%!A(MISSING)crossplanecontrib%!F(MISSING)provider-ansible%!A(MISSING)pull&service=xpkg.upbound.io: unexpected status code 404 Not Found: GET https://xpkg.upbound.io/service/token?scope=repository%!A(MISSING)crossplanecontrib%!F(MISSING)provider-ansible%!A(MISSING)pull&service=xpkg.upbound.io: unexpected status code 404 Not Found
```
From [v1.15 release notes](https://github.com/crossplane/crossplane/releases/tag/v1.15.0), 
> The default registry that Crossplane's package manager will install packages from has changed to xpkg.upbound.io from index.docker.io

The workaround mentioned in those release notes is to specify the registry explicitly with e.g. `index.docker.io/crossplanecontrib/provider-ansible:v0.6.0`. This works, but I figure users are gonna get frustrated when copy-pasted examples don't work and they have to spend time debugging just to find out they had to add` index.docker.io` there. So ideally, provider-ansible artifacts should be published to xpkg.upbound.io 

### How can we reproduce it?

Deploy provider-ansible with Crossplane v.1.15.0 or higher and `Provider` yaml like this
```
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: '20'
  name: provider-ansible
spec:
  runtimeConfigRef:
    name: provider-ansible-config
    package: crossplanecontrib/provider-ansible:v0.6.0
```

### What environment did it happen in?
Crossplane version: 
1.16.0
