### ISSUE TITLE
Unable to trigger delete/cleanup code

### ISSUE THREAD

**Issue by jf1cloutier** [crossplane-contrib/provider-ansible#362]
### What happened?
I'm trying to trigger cleanup code on composite-resource deletion. According to the doc, I can use the variable 'ansible_provider_meta.{managed_resource}.state' to detect when the ansibleRun object get deleted. I created a simple ansibleRun object which only output debug information. I can see the expected debug output on ansibleRun creation but I don't see anything at all when the ansibleRun object is deleted. I read the doc few time and I believe I have the syntax right but I can't get the playbook to be triggered on ansibleRun deletion (on crossplane delete lifecycle event)

### How can we reproduce it?
- Apply this simple configuration:

``` yaml
apiVersion: ansible.crossplane.io/v1alpha1
kind: AnsibleRun
metadata:
  annotations:
    ansible.crossplane.io/runPolicy: ObserveAndDelete
  name: deletetest
spec:
  forProvider:
    playbookInline: |
      ---
      - hosts: localhost
        tasks:
          - name: debug adding
            debug:
              msg: Adding
            when: ansible_provider_meta.deletetest.state == 'present'
          - name: debug removing
            debug:
              msg: Removing
            when: ansible_provider_meta.deletetest.state != 'present'
  providerConfigRef:
    name: default
---
apiVersion: ansible.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: default
spec: {}
```

- Look at the log of the ansible-provider pod for output of this playbook run. 
- delete ansibleRun object deletetest
- Observe the log and nothing is triggered. Impossible to perform cleanup action

I might have misunderstood the documentation, but it seems using the ObserveAndDelete policy and using 'ansible_provider_meta.{managed_resource}.state != present' should allow to trigger one playbook run on resource deletion.

### What environment did it happen in?
provider-ansible version: xpkg.upbound.io/crossplane-contrib/provider-ansible:v0.6.0
Crossplane version: Server Version: v1.18.0-up.1
Kubernetes version: Server Version: v1.32.0

**Comment by jf1cloutier** [comment]
Update on this, I am now able to trigger deletion/cleanup but it seems there is a deletion loop.
For my previous message, this wasn't an appropriate way to trigger deletion. The ansibleRun object needs to be created through composition as a managedResouce and composition needs to create the managed resource with deletionPolicy=Delete to make sure the cleanup/deletion will be done. 

Here are the manifests I am using to trigger this:
```yaml
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-ansible
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-ansible:v0.6.0
---
apiVersion: ansible.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: default
spec: {}
---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xtestansibles.ora.crossplane.io
spec:
  group: ora.crossplane.io
  names:
    kind: XTestAnsible
    plural: xtestansibles
  claimNames:
    kind: TestAnsible
    plural: testansibles
  versions:
  - name: v1beta1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              policyName:
                type: string
            required:
              - policyName

---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: policy-ansible
spec:
  compositeTypeRef:
    apiVersion: ora.crossplane.io/v1beta1
    kind: XTestAnsible
  mode: Pipeline
  pipeline:
    - step: policy-ansible
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            {{- $policyName := .observed.composite.resource.spec.policyName }}
            ---
            apiVersion: ansible.crossplane.io/v1alpha1
            kind: AnsibleRun
            metadata:
              annotations:
                ansible.crossplane.io/runPolicy: ObserveAndDelete
                gotemplating.fn.crossplane.io/composition-resource-name: policy-{{ $policyName }} 
              name: policy-{{ $policyName }}
            spec:
              deletionPolicy: Delete
              forProvider:
                playbookInline: |
                  ---
                  - hosts: localhost
                    tasks:
                      - name: debug adding
                        debug:
                          msg: Adding
                        when: ansible_provider_meta.get('policy-{{ $policyName }}').state == 'present'
                      - name: debug removing
                        debug:
                          msg: Removing
                        when: ansible_provider_meta.get('policy-{{ $policyName }}').state != 'present'
    - step: ready
      functionRef:
        name: function-auto-ready
---
apiVersion: ora.crossplane.io/v1beta1
kind: TestAnsible
metadata:
  name: test-policy-patate44
spec:
  policyName: patate44

```

After applying those manifests, I can see from the provider pod logs that ansible playbook is running and debug task is output is "Adding" (which is what I expected).

If I delete the claim `kubectl delete TestAnsible test-policy-patate44`, then the ansible playbook is ran again but this time the debug output is "Removing" (this is the expected behavior to be able to cleanup resources). The claim get deleted, the XR(composite resource) get delete and it looks like it is trying to delete the manage resource (ansibleRun object) but this one never gets deleted. On the provider pod log, I can see at every minute or so that the playbook runs for this ansibleRun object and debug output is "Removing".

Only way I can break this loop is to remove the finalizer on the ansibleRun object which will allow the ansibleRun object to get deleted from K8S and then the provider is stable (not looping on deletion anymore).

Can anyone can suggest a way to make this clean so a claim deletion doesn't end up in a loop where the ansibleRun is never deleted?

**Comment by estenrye** [comment]
Reproduced independently on **v0.8.0** (`xpkg.upbound.io/crossplane-contrib/provider-ansible:v0.8.0`), with a different — and possibly regressed — symptom than what's described above.

Test setup: an `AnsibleRun` with `spec.deletionPolicy: Delete` and the `ansible.crossplane.io/runPolicy: ObserveAndDelete` annotation @jf1cloutier identified, running a playbook that unconditionally logs the full `ansible_provider_meta` variable to a file on the target host, rather than gating on a `when:` condition — so the result doesn't depend on getting that condition right.

```yaml
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-ansible
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-ansible:v0.8.0
---
apiVersion: ansible.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: default
spec: {}
---
apiVersion: ansible.crossplane.io/v1alpha1
kind: AnsibleRun
metadata:
  name: ansible-delete-mechanism-test
  annotations:
    ansible.crossplane.io/runPolicy: ObserveAndDelete
spec:
  deletionPolicy: Delete
  forProvider:
    inventoryInline: |
      localhost ansible_connection=local
    playbookInline: |
      - hosts: all
        tasks:
          - name: Show whatever ansible_provider_meta actually looks like on this run
            ansible.builtin.debug:
              var: ansible_provider_meta
          - name: Record this run to a marker file (append, timestamped)
            ansible.builtin.shell:
              cmd: >-
                echo "$(date -Iseconds) ansible_provider_meta={{ ansible_provider_meta | default('UNDEFINED') | to_json }}"
                >> /tmp/ansible-delete-mechanism-test.log
  providerConfigRef:
    name: default
```

Steps and results:
1. `kubectl apply -f test.yaml` — logs and the marker file both show `ansible_provider_meta.ansible-delete-mechanism-test.state == 'present'`, as expected.
2. `kubectl delete ansiblerun ansible-delete-mechanism-test` — the object disappears from the API in ~5 seconds; no blocking wait, no visible second reconcile in the controller logs.
3. Re-reading `/tmp/ansible-delete-mechanism-test.log` afterward (via a separate, later `AnsibleRun`) shows only the original `present` line — no `absent` (or any second) entry was ever written.
4. Repeated the whole sequence with and without the `runPolicy: ObserveAndDelete` annotation — same result both times: no delete-triggered playbook run at all.

So on v0.8.0 we don't see the deletion loop @jf1cloutier hit on v0.6.0 (which at least indicates the mechanism *was* triggering there) — instead the delete-triggered run appears to never fire in the first place, even with the annotation in place. Possibly a regression between v0.6.0 and v0.8.0, possibly something else changed about how/where the annotation needs to be set (e.g. only via a Composition-templated `AnsibleRun` rather than applied directly, which is what the manifest above does) — flagging in case it's useful for narrowing down where this broke. Happy to share full controller logs if helpful.
