### ISSUE TITLE
aws kafka: add support for single scram secret association

### ISSUE THREAD

**Issue by ronaldoalvescosta** [crossplane-contrib/provider-ansible#367]
Actual behavior:

apiVersion: kafka.aws.upbound.io/v1beta1
kind: ScramSecretAssociation
if spec.forProvider.secretArnList is empty all aws secretsmanager secrets are removed from msk association.

Example:

```yaml
apiVersion: secretsmanager.aws.upbound.io/v1beta1
kind: Secret
metadata:
  labels:
    testing.upbound.io/secret-name: ronaldo
  name: ronaldo
spec:
  forProvider:
    name: AmazonMSK_ronaldo
    recoveryWindowInDays: 14
    region: us-east-1
    kmsKeyId: 1111-2222-3333
---
apiVersion: kafka.aws.upbound.io/v1beta1
kind: ScramSecretAssociation
metadata:
  labels:
    testing.upbound.io/secret-name: ronaldo
  name: ronaldo
spec:
  forProvider:
    clusterArn: arn:::xxx
    region: us-east-1
    secretArnList: [] #Existing secrets associated on MSK not referenced here will be disassociated from the cluster
    secretArnSelector:
      matchLabels:
        testing.upbound.io/secret-name: ronaldo
```

Desired behavior or feature:

Please make possible to do aws_msk_single_scram_secret_association like terraform made here on recent release:

https://github.com/hashicorp/terraform-provider-aws/blob/v5.81.0/CHANGELOG.md
https://github.com/hashicorp/terraform-provider-aws/pull/37056
https://github.com/hashicorp/terraform-provider-aws/issues/16791
