### ISSUE TITLE
Support mixed references to roles and collections when defining requirements

### ISSUE THREAD

**Issue by morningspace** [crossplane-contrib/provider-ansible#81]
### What problem are you facing?

It looks in the current implementation, when defining roles and collections as requirements, they are mutually exclusive, while in Ansible requirements.yml, it supports mixed of both.

### How could Crossplane help solve your problem?

We can support it in next releases, so that aligns with what Ansible requirements.yml natively support. For example:

```yaml
apiVersion: ansible.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: provider-config-example
spec:
  requirements: |
    ---
    roles:
      # Install a role from Ansible Galaxy.
      - name: sample_namespace.sample_role
        version: 0.1.0
    collections:
      # Install a collection from Ansible Galaxy.
      - name: sample_namespace.sample_collection
        version: 0.1.0
        source: https://galaxy.ansible.com
```
